export const dataProduct = [
  {
    id_produk: '9',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Jengkol (Archidendron pauciflorum)',
    konten_produk: '',
    tanggal_produk: '2020-03-19 20:50:49',
    gambar_produk: '20200506100256.png',
    status_produk: '0',
    id_user: '244',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1750,
    stok: '125000',
  },
  {
    id_produk: '11',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Petai (Parkia speciosa)',
    konten_produk: '',
    tanggal_produk: '2020-03-19 20:52:17',
    gambar_produk: '20200506101103.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2500,
    stok: '122000',
  },
  {
    id_produk: '23',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Durian (Durio zibethinus)',
    konten_produk: '',
    tanggal_produk: '2020-03-19 21:01:16',
    gambar_produk: '20200506101222.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '46000',
  },
  {
    id_produk: '28',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Pompa Punggung JUFA',
    konten_produk: '',
    tanggal_produk: '2020-05-02 15:42:30',
    gambar_produk: '20200502160229.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2500000,
    stok: '10',
  },
  {
    id_produk: '29',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Kepyok',
    konten_produk: `Bahan gagang rotan manau
      Bahan kipas kawat jenis kawat ram ayam galvanis`,
    tanggal_produk: '2020-05-02 15:43:46',
    gambar_produk: '20200502160345.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 250000,
    stok: '10',
  },
  {
    id_produk: '30',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Cangkul Garu',
    konten_produk:
      '<ul>\r\n\t<li>Bahan plat besi 23 mm</li>\r\n\t<li>Gagang kayu olahan</li>\r\n</ul>\r\n',
    tanggal_produk: '2020-05-02 15:44:46',
    gambar_produk: '20200502160716.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 275000,
    stok: '10',
  },
  {
    id_produk: '31',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Sekop',
    konten_produk:
      '<ul>\r\n\t<li>Bahan plat besi 23 mm</li>\r\n\t<li>Gagang kayu olahan</li>\r\n</ul>\r\n',
    tanggal_produk: '2020-05-02 15:45:05',
    gambar_produk: '20200502161111.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 250000,
    stok: '10',
  },
  {
    id_produk: '32',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Helm Pemadam',
    konten_produk: '<p>Warna merah/orange</p>\r\n',
    tanggal_produk: '2020-05-02 15:45:37',
    gambar_produk: '20200502161325.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 150000,
    stok: '10',
  },
  {
    id_produk: '33',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Sarung Tangan Pemadam',
    konten_produk:
      '<ul>\r\n\t<li>Kain</li>\r\n\t<li>Tahan panas</li>\r\n</ul>\r\n',
    tanggal_produk: '2020-05-02 15:46:15',
    gambar_produk: '20200502161553.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 125000,
    stok: '10',
  },
  {
    id_produk: '34',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Baju Dan Celana Lapangan',
    konten_produk:
      '<ul>\r\n\t<li>Kain America drill</li>\r\n\t<li>Warna merah</li>\r\n\t<li>Segala ukuran</li>\r\n</ul>\r\n',
    tanggal_produk: '2020-05-02 15:46:50',
    gambar_produk: '20200502161717.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 225000,
    stok: '10',
  },
  {
    id_produk: '35',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Kacamata Pemadam',
    konten_produk: '',
    tanggal_produk: '2020-05-02 15:47:19',
    gambar_produk: '20200502161850.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 150000,
    stok: '10',
  },
  {
    id_produk: '36',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Sepatu Lapangan',
    konten_produk:
      '<ul>\r\n\t<li>Bahan kulit</li>\r\n\t<li>Alas karet anti slip terdapat besi safety penahan berat</li>\r\n</ul>\r\n',
    tanggal_produk: '2020-05-02 15:47:46',
    gambar_produk: '20200502162019.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 275000,
    stok: '10',
  },
  {
    id_produk: '37',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Hammock',
    konten_produk:
      '<ul>\r\n\t<li>Bahan parasut</li>\r\n\t<li>Bahan kain dalam polar berbulu hangat</li>\r\n</ul>\r\n',
    tanggal_produk: '2020-05-02 15:48:07',
    gambar_produk: 'default.jpg',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 175000,
    stok: '10',
  },
  {
    id_produk: '38',
    id_kategori_produk: '12',
    id_anggota: '0',
    judul_produk: 'Kantong Air Portable',
    konten_produk:
      '<ul>\r\n\t<li>Bahan terpal korea</li>\r\n\t<li>Kapasitas 1000 l, 3000 l</li>\r\n</ul>\r\n',
    tanggal_produk: '2020-05-02 15:48:36',
    gambar_produk: '20200502162158.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 7000000,
    stok: '10',
  },
  {
    id_produk: '39',
    id_kategori_produk: '11',
    id_anggota: '0',
    judul_produk: 'Pupuk Organik Blok',
    konten_produk: '<p>Jumlah Stock 4.000 Biji</p>\r\n',
    tanggal_produk: '2020-05-02 16:33:26',
    gambar_produk: '20200502163851.png',
    status_produk: '0',
    id_user: '244',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 5500,
    stok: '3000',
  },
  {
    id_produk: '40',
    id_kategori_produk: '11',
    id_anggota: '0',
    judul_produk: 'Pupuk Organik Curah/Kg',
    konten_produk: '<p>Jumlah Stock 1.000&nbsp;Kg</p>\r\n',
    tanggal_produk: '2020-05-02 16:34:03',
    gambar_produk: '20200502164028.png',
    status_produk: '0',
    id_user: '244',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '800',
  },
  {
    id_produk: '41',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Mahoni (Swietenia sp)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>70-100</td>\r\n\t\t\t<td>15x20</td>\r\n\t\t\t<td>Juni 2019</td>\r\n\t\t\t<td>10-12</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 16:56:14',
    gambar_produk: '20200506101414.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 6000,
    stok: '15000',
  },
  {
    id_produk: '42',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Mahoni (Swietenia sp)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-60</td>\r\n\t\t\t<td>10x15 dan 9x13</td>\r\n\t\t\t<td>Januari dan Februari 2020</td>\r\n\t\t\t<td>3-4</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 16:58:28',
    gambar_produk: '20200506101639.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1750,
    stok: '332000',
  },
  {
    id_produk: '43',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Gaharu (Aquilaria malaccensis)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>50-80</td>\r\n\t\t\t<td>10x15 dan 8x12</td>\r\n\t\t\t<td>April 2019</td>\r\n\t\t\t<td>12</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 16:59:32',
    gambar_produk: '20200506101812.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 4000,
    stok: '10000',
  },
  {
    id_produk: '44',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Gaharu (Aquilaria malaccensis)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-50</td>\r\n\t\t\t<td>10x15 dan 8x12</td>\r\n\t\t\t<td>November dan Desember 2019</td>\r\n\t\t\t<td>4-6</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:00:43',
    gambar_produk: '20200506101837.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '25000',
  },
  {
    id_produk: '45',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Nangka (Artocarpus heterophyllus)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>60-70</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Desember 2019</td>\r\n\t\t\t<td>4</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:01:34',
    gambar_produk: '20200506102022.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '20000',
  },
  {
    id_produk: '46',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Sengon Buto (Enterolobium cyclocarpum)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>40-80</td>\r\n\t\t\t<td>10x15 dan 8x12</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:02:44',
    gambar_produk: '20200506102345.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '130000',
  },
  {
    id_produk: '47',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Johar (Cassia siamea)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>40-50</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Desember 2019</td>\r\n\t\t\t<td>4</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:03:39',
    gambar_produk: '20200506102541.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '5000',
  },
  {
    id_produk: '48',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Jabon  Putih (Anthocephalus cadamba)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-60</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Januari dan Februari 2020</td>\r\n\t\t\t<td>\r\n\t\t\t<p>3-4</p>\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:04:44',
    gambar_produk: '20200506102726.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3000,
    stok: '6000',
  },
  {
    id_produk: '49',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Karet (Hevea brasiliensis) Cabutan',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>60-100</td>\r\n\t\t\t<td>10x15 dan 8x12</td>\r\n\t\t\t<td>Februari dan Maret 2020</td>\r\n\t\t\t<td>2-3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:10:37',
    gambar_produk: '20200506102921.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1100,
    stok: '185000',
  },
  {
    id_produk: '50',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Karet (Hevea brasiliensis) Okulasi ',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-50</td>\r\n\t\t\t<td>15x20 dan 15x25</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:11:29',
    gambar_produk: '20200506102950.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 7000,
    stok: '5000',
  },
  {
    id_produk: '51',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Minyak Kayu Putih (Melaleuca leucadendron)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-53</td>\r\n\t\t\t<td>10x15 dan 8x12</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:12:39',
    gambar_produk: '20200506103212.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3500,
    stok: '43000',
  },
  {
    id_produk: '52',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Minyak Kayu Putih (Melaleuca leucadendron)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>10</td>\r\n\t\t\t<td>9x13</td>\r\n\t\t\t<td>Maret 2020</td>\r\n\t\t\t<td>1</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:13:27',
    gambar_produk: '20200506103339.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3500,
    stok: '5000',
  },
  {
    id_produk: '53',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Ketapang (Terminalia catappa)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>40-50</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:14:35',
    gambar_produk: '20200506103617.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1300,
    stok: '8000',
  },
  {
    id_produk: '54',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Kemiri (Terminalia catappa)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>50-70</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:15:17',
    gambar_produk: '20200506103832.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3500,
    stok: '10000',
  },
  {
    id_produk: '55',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Kopi Arabika (Coffea arabica)',
    konten_produk:
      '<p>&nbsp;</p>\r\n\r\n<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-50</td>\r\n\t\t\t<td>10x15 dan 8x12</td>\r\n\t\t\t<td>Januari dan Februari 2020</td>\r\n\t\t\t<td>3-4</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:16:11',
    gambar_produk: '20200506104044.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1600,
    stok: '19000',
  },
  {
    id_produk: '56',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Sungkai Stek (Peronema canescens) ',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>40-100</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Januari dan Februari 2020</td>\r\n\t\t\t<td>3-4</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:17:02',
    gambar_produk: '20200502171702.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2500,
    stok: '23000',
  },
  {
    id_produk: '57',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Langsat (Lansium domesticum)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>25-30</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Desember 2019</td>\r\n\t\t\t<td>5</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:17:38',
    gambar_produk: '20200506104419.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3000,
    stok: '5000',
  },
  {
    id_produk: '58',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Trembesi (Samanea saman)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-70</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:18:55',
    gambar_produk: '20200506104551.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '30000',
  },
  {
    id_produk: '59',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Randu (Ceiba pentandra)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-40</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Februari dan Maret 2020</td>\r\n\t\t\t<td>2-3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:20:03',
    gambar_produk: '20200506104757.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '6500',
  },
  {
    id_produk: '60',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Kasturi (Mangifera casturi)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30</td>\r\n\t\t\t<td>10x15 dan 9x13</td>\r\n\t\t\t<td>Maret 2020</td>\r\n\t\t\t<td>2</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:21:00',
    gambar_produk: '20200506104954.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2500,
    stok: '2000',
  },
  {
    id_produk: '61',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Kayu Manis (Cinnamomum verum)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>15</td>\r\n\t\t\t<td>9x13</td>\r\n\t\t\t<td>Maret 2020</td>\r\n\t\t\t<td>2</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:21:59',
    gambar_produk: '20200502172159.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3500,
    stok: '2000',
  },
  {
    id_produk: '62',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Sengon Laut (Albizia chinensis)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-40</td>\r\n\t\t\t<td>10x15 dan 8x12</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:23:16',
    gambar_produk: '20200502172316.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '10000',
  },
  {
    id_produk: '63',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Sengon Laut (Albizia chinensis)',
    konten_produk:
      '<p>&nbsp;</p>\r\n\r\n<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>5</td>\r\n\t\t\t<td>8x12</td>\r\n\t\t\t<td>April 2020</td>\r\n\t\t\t<td>1</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:24:31',
    gambar_produk: '20200502172431.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '15000',
  },
  {
    id_produk: '64',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Cempedak (Artocarpus integer)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-40</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:25:21',
    gambar_produk: '20200502172521.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '5000',
  },
  {
    id_produk: '65',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Alaban (Vitex pubescens)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-40</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:26:09',
    gambar_produk: '20200506105405.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '5000',
  },
  {
    id_produk: '66',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Mangga (Mangifera indica) Biji',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>30-50</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>Januari 2020</td>\r\n\t\t\t<td>4</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:27:29',
    gambar_produk: '20200502172729.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3500,
    stok: '2000',
  },
  {
    id_produk: '67',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Mangga (Mangifera indica) Okulasi ',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>40-50</td>\r\n\t\t\t<td>15x20</td>\r\n\t\t\t<td>Februari 2020</td>\r\n\t\t\t<td>3</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:28:20',
    gambar_produk: '20200502172820.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 25000,
    stok: '2000',
  },
  {
    id_produk: '68',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Pulai (Alstonia scholaris)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>8x13</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:29:08',
    gambar_produk: '20200502172908.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '350000',
  },
  {
    id_produk: '69',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Pantung (Dyera costulata)',
    konten_produk:
      '<p>&nbsp;</p>\r\n\r\n<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>50</td>\r\n\t\t\t<td>8x13</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:29:58',
    gambar_produk: '20200502172958.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2500,
    stok: '500000',
  },
  {
    id_produk: '70',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Balangeran (Shorea balangeran)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>8x13</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:30:53',
    gambar_produk: '20200502173053.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 1500,
    stok: '350000',
  },
  {
    id_produk: '71',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Jambu-Jambu',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>50</td>\r\n\t\t\t<td>10x15 dan 8x13</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:31:48',
    gambar_produk: '20200502173148.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '50000',
  },
  {
    id_produk: '72',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Tumih',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>55-60</td>\r\n\t\t\t<td>10x15 dan 8x13</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:32:31',
    gambar_produk: '20200502173231.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 3000,
    stok: '30000',
  },
  {
    id_produk: '73',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Gerunggang',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:33:16',
    gambar_produk: '20200502173316.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2500,
    stok: '20000',
  },
  {
    id_produk: '74',
    id_kategori_produk: '7',
    id_anggota: '0',
    judul_produk: 'Galam (Melaleuca leucadendron)',
    konten_produk:
      '<table border="1" bordercolor="#ccc" cellpadding="5" cellspacing="0" style="border-collapse:collapse">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td>Tinggi (cm)</td>\r\n\t\t\t<td>Ukuran Polibag</td>\r\n\t\t\t<td>Bulan Sapih</td>\r\n\t\t\t<td>Umur (Bulan)</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>10x15</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t\t<td>&nbsp;</td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n',
    tanggal_produk: '2020-05-02 17:34:09',
    gambar_produk: '20200502173409.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 2000,
    stok: '20000',
  },
  {
    id_produk: '75',
    id_kategori_produk: '13',
    id_anggota: '0',
    judul_produk: 'Madu Kelulut/Box',
    konten_produk: '1 box terdiri dari 3 botol masing-masing 85 gr',
    tanggal_produk: '2020-05-03 21:11:44',
    gambar_produk: '20200504145356.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 110000,
    stok: '200',
  },
  {
    id_produk: '76',
    id_kategori_produk: '13',
    id_anggota: '0',
    judul_produk: 'Madu Mangrove/Box',
    konten_produk: '1 box berisi 3 botol masing-masing 85 gr',
    tanggal_produk: '2020-05-04 12:55:04',
    gambar_produk: '20200504132655.png',
    status_produk: '0',
    id_user: '241',
    satuan: '',
    ukuran: '',
    hpp: '0',
    harga_jual: 110000,
    stok: '500',
  },
];
